name: Release Library
# Job will only run on push to the main branch after the test job has passed

on:
  push:
    branches: ['main']
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'assets/**'
      - '*.yml'
      - '*.json'
      - '*.config'
      - '!packages/**'
  workflow_dispatch:
    inputs: {}

concurrency:
  group: 'release-library'
  cancel-in-progress: false

env:
  ARTIFACT_NAME: 'build-lib-artifact'

jobs:
  build:
    if: |
      github.ref == 'refs/heads/main' &&
      github.event.repository.fork == false &&
      github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: FSI_DEP_NodeJs
    strategy:
      matrix:
        package: [marked-extended-tables]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun - Version ${{ vars.BUN_VERSION }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}
          registry-url: 'https://registry.npmjs.org/'
          scope: ${{ vars.NPM_ORG }}

      - name: Install dependencies
        run: bun install

      - name: Build ${{ matrix.package }} package
        run: |
          cd packages/${{ matrix.package }}
          bun run prepare

      - name: Get package version
        id: get_version
        run: echo "VERSION=$(jq -r .version < packages/${{ matrix.package }}/package.json)" >> $GITHUB_ENV

      - name: Determine tag
        id: determine_tag
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          if [[ "$VERSION" == *"-beta"* ]]; then
            echo "TAG=beta" >> $GITHUB_OUTPUT
          elif [[ "$VERSION" == *"-alpha"* ]]; then
            echo "TAG=alpha" >> $GITHUB_OUTPUT
          elif [[ "$VERSION" == *"-rc"* ]]; then
            echo "TAG=rc" >> $GITHUB_OUTPUT
          elif [[ "$VERSION" == *"-next"* ]]; then
            echo "TAG=next" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Release to NPM registry 🚀 - ${{ steps.get_version.outputs.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/${{ matrix.package }}
          bun publish --tag ${{ steps.determine_tag.outputs.TAG }} --access public || echo "Package already published in NPM, skipping..."

      - name: Set up Bun - Version ${{ vars.BUN_VERSION }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: ${{ vars.NPM_ORG }}
          always-auth: true

      - name: Release to GitHub NPM registry 🚀 - ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GH_TOKEN }}
        run: |
          cd packages/${{ matrix.package }}
          bun publish --tag ${{ steps.determine_tag.outputs.TAG }} && bun semantic-release || echo "Package already published in GitHub NPM, skipping..."
